config/routes.rb
Rails.application.routes.draw do

  resources :topics
  resources :captions
  resources :comic_topics
  resources :comics
  resources :users
  root to: "application#home" 

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "/welcome", to: "sessions#new"
  get "authorized", to: "sessions#page_requires_login"
  get "/logout", to: "sessions#destroy"
  # get "/new", to: "sessions#new"
  
  patch "/captions/:id/like", to: "captions#like"

end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :user
  has_many :comic_topics
  has_many :topics, through: :comic_topics
  has_many :captions

  def total_likes 
    likes = 0
    self.captions.each do |caption| 
      likes += caption.likes 
    end
    likes 
  end

  def self.top(x)
    Comic.all.sort_by {|comic| -comic.total_likes}.slice(0,x)
  end

  def funniest_caption_order
    self.captions.sort_by{|caption| -caption.likes}
  end

  def funniest_caption 
    if !self.captions.empty?
      funniest_caption_order.first
    end 
  end

  def self.sort_by_latest
    self.all.sort_by {|comic| comic.created_at}.reverse
  end

  def self.sort_by_funniest
    self.all.sort_by {|comic| -comic.total_likes}
  end

  def self.latest(x)
    sorted = self.sort_by_latest
    sorted.slice(0, x)
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController

  before_action :current_comic, only: [:show, :destroy, :edit, :update, :create_joiners]

  def index
    @comics = Comic.all 
    # @top_5_comics = Comic.top_5
    @topics = Topic.all 
    @random_comic = Comic.all.sample 
  end

  def show 
    @user = User.find(@comic.user_id)
    @captions = @comic.captions
    @topics = @comic.topics
    @random_comic = Comic.all.sample
  end

  def new 
    @comic = Comic.new
    @topics = Topic.all.sort_by{|topic| topic.label}
  end

  def create 
    # byebug
    @comic = Comic.create(image_url: comic_params[:image_url], user_id: session[:user_id]) #user has to be updated to current user
    if comic_params[:topic_name] == ""
      if comic_params[:topic_ids].count > 1
        create_joiners
      end
    else 
      new_topic = Topic.create(label: comic_params[:topic_name].capitalize)
      ComicTopic.create(comic_id: @comic.id, topic_id: new_topic.id)
      if comic_params[:topic_ids].count > 1
        create_joiners
      end
    end
    redirect_to comic_path(@comic)
  end

  
  def edit 
    @topics = Topic.all.sort_by{|topic| topic.label}
  end

  def update 
    @comic.comic_topics.each {|comic_tag| comic_tag.destroy}
    if comic_params[:topic_name] == ""
      if comic_params[:topic_ids].count > 1
        create_joiners
      end
    else 
      new_topic = Topic.create(label: comic_params[:topic_name].capitalize)
      ComicTopic.create(comic_id: @comic.id, topic_id: new_topic.id)
      if comic_params[:topic_ids].count > 1
        create_joiners
      end
    end
    redirect_to comic_path(@comic)
  end

  def destroy
    @comic.comic_topics.each do |comic_topic|
      comic_topic.destroy
    end
    @comic.destroy
    redirect_to comics_path
  end

  private 

  def current_comic
    @comic = Comic.find(params[:id])
  end

  def comic_params 
    params.require(:comic).permit(:image_url, :topic_name, topic_ids:[])
  end

  def create_joiners 
    comic_params[:topic_ids].reject(&:blank?).each do |topic_id|
      ComicTopic.create(comic_id: @comic.id, topic_id: topic_id)
    end
  end




end

app/views/comics/edit.html.erb
<div>
<h1>CAPTION IT!</h1>

<img src="<%= @comic.image_url %>" alt="Image did not load", height="200">


<%= form_with model: @comic do |f| %>
  <%# f.label :image_url %>
  <%# f.text_field :image_url %> <br><br>
  <%= f.label :tags %> <br>
  <%= f.collection_check_boxes :topic_ids, @topics, :id, :label  %><br><br>
  <%= f.label "New tag:" %>
  <%= f.text_field :topic_name %><br><br>
  <%= f.submit "Update Tags" %>
<% end %>

<%= form_with url: "/comics/#{@comic.id}", method: :delete do |f|  %>
    <%= f.submit "Delete Image" %>
  <% end %>

</div>

app/views/comics/index.html.erb
<div>

<h1>CAPTION IT!</h1>


<h2>All Images: </h2>





<% @comics.each do |comic| %>
  <a href="/comics/<%= comic.id %>">
    <img src="<%= comic.image_url %>" alt="Image did not load." height="100">
  </a>
<% end %>

</div>


<!-- 
<br>
<br>
<button>
  <a href="/comics/new">
    <div>Add New Image</div>
  </a>
</button>
<br>
<button>
  <a href="/comics/<%= @random_comic.id %>">
    <div>Shuffle</div>
  </a>
</button>
<br>
<button>
  <a href="/topics">
    <div>Categories</div>
  </a>
</button>
<br>
<button>
  <a href="/">
    <div>Home</div>
  </a>
</button>
<br>
<button>
  <a href="/users">
    <div>Users</div>
  </a>
</button>
<%= form_with url: "/logout", method: "delete" do |f| %>
  <%= f.submit "logout" %>
<% end %>

-->

app/views/comics/new.html.erb
<div>

<h1>CAPTION IT!</h1>


<%= form_with model: @comic do |f| %>
  <%= f.label "Link to Image:" %>
  <%= f.text_field :image_url, class: "text_field"%> <br><br>
  <%= f.label "Tags:" %> <br>
  <%= f.collection_check_boxes :topic_ids, @topics, :id, :label, class: ".checkbox_grid" %><br>
  <%# f.collection_check_boxes :topic_ids, @topics, :id, :label, class: ".checkbox_grid" %><br>
  <%= f.label "New tag:" %>
  <%= f.text_field :topic_name %><br><br>
  <%= f.submit  %>
<% end %>

</div>

app/views/comics/show.html.erb
<div>

<h1>CAPTION IT!</h1>


<img src= <%= @comic.image_url %> alt="Image not loaded" height="200"><br/>

<label>Total Knee Slaps: <%= @comic.total_likes %></label><br>
<label>Uploaded by: <%= link_to "#{@user.username}", user_path(@user) %> </label><br>
<label>Tags: </label>
<% @topics.each do |topic| %>
  <a href="/topics/<%= topic.id %>">
    <%= topic.label %>
  </a>
<% end %>

<h4>Captions: </h4>


<% @comic.funniest_caption_order.each do |caption| %>
  <%= caption.text %> -<%= link_to "#{User.find(caption.user_id).username}", user_path(caption.user_id)%> <br>
     <%= form_with url:"/captions/#{caption.id}/like", class: 'inline_form', method: "patch" do |f| %>
      <%= f.hidden_field :page, :value => "/comics/#{@comic.id}" %>
      <%= f.submit "#{caption.likes} Knee Slaps" %> 
    <% end %> 
    <% if caption.user_id == session[:user_id]%>
      <button> <%= link_to "Edit", edit_caption_path(caption) %> </button>
    <% end %> <br><br>
<% end %> <br><br>

<%= form_with url:"/captions", method: "post"  do |f| %>
  <%= f.label :" "%>
  <%= f.text_field :text, class: 'text_field' %>
  <%#= f.hidden_field :likes, :value => 0 %>
  <%= f.hidden_field :comic_id, :value => @comic.id %>
  <%= f.submit "Add Caption" %>
<% end %> <br><br>



<% if @comic.user_id == session[:user_id] %>
  <button>
    <a href="/comics/<%= @comic.id %>/edit"> Edit Image</a>
  </button>
<% end %>



</div>

<!-- 


<br>
<br>

<br>
<button>
  <a href="/comics">
    <div>All Images</div>
  </a>
</button>
<br>
<button>
  <a href="/topics">
    <div>All Categories</div>
  </a>
</button>
<br>
<button>
  <a href="/comics/<%= @random_comic.id %>">
    <div>Shuffle</div>
  </a>
</button>
<br>
<button>
  <a href="/">
    <div>Home</div>
  </a>
</button>

<%= form_with url: "/logout", method: "delete" do |f| %>
  <%= f.submit "logout" %>
<% end %>

-->




</div>